spring.application.name=discovery-service
server.port=8761


eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.server.enable-self-preservation=false

spring.cloud.config.enabled=false
# Logging pattern with trace and span IDs
logging.pattern.level=%5p [${spring.application.name},%X{traceId},%X{spanId}]

# Actuator endpoint exposure
management.endpoints.web.exposure.include=health,info,metrics,env,loggers

# Health details
management.endpoint.health.show-details=always

# Zipkin tracing endpoint
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans

# Sampling probability (100%)
management.tracing.sampling.probability=1.0

# Propagation type
management.tracing.propagation.type=B3
